// Game-id → display-name lookup. Source data is generated by
// scripts/build-names.ts from the StS2 localization JSON and bundled
// into the JS at build time (see web/src/lib/data/names.json).

import names from '$lib/data/names.json';

const lookup = names as Record<string, string>;

export function displayName(id: string): string | undefined {
	return lookup[id];
}
